using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using FYP_Project.Database;

namespace FYP_Project.Forms
{
    public partial class LoginForm : Form
    {
        private DatabaseLoader databaseLoader;

        public LoginForm()
        {
            InitializeComponent();

            //need to subscribe to event here because Designer file is generated by compiler
            textBoxPassword.KeyPress += new System.Windows.Forms.KeyPressEventHandler(textBox_TextChanged);
            textBoxUsername.KeyPress += new System.Windows.Forms.KeyPressEventHandler(textBox_TextChanged);
            textBoxPassword.TextChanged += textBox_ResizeToContent;
            textBoxUsername.TextChanged += textBox_ResizeToContent;
            

            string serverName = "46.22.134.194";
            string port = "5432";
            string userName = "u1300377_wells4z";
            string password = "_Harrington22";
            string databaseName = "WellsForZoe_fyp";
            string connString = String.Format("Server={0};Port={1}; User Id={2};Password={3};Database={4};Ssl=True;SslMode=Prefer;Timeout=5;CommandTimeout=5;Pooling=False;",
                    serverName, port, userName, password, databaseName);
            databaseLoader = new DatabaseLoader(connString, NetworkChecker.LastStatus);
            

            textBoxUsername.Select();
            
        }

        private void loginBtn_Click(object sender, EventArgs e)
        {
            var email = textBoxUsername.Text;
            var password = textBoxPassword.Text;

            if(string.IsNullOrWhiteSpace(email) || !isEmailValid(email))
            {
                errorDisplayLbl.Text = "Must be a valid email";
            }
            else if (string.IsNullOrWhiteSpace(password))
            {
                errorDisplayLbl.Text = "Must enter a password";
            }
            else
            {
                try
                {
                    var success = databaseLoader.TryLogin(email, password);
                    if (success)
                    {
                        this.DialogResult = System.Windows.Forms.DialogResult.OK;
                        this.Close();
                        this.Dispose();
                    }
                    else
                    {
                        errorDisplayLbl.Text = "Password does not match the record";
                    }
                }
                catch (Exception ex)
                {
                    errorDisplayLbl.Text = ex.Message;
                }
            }
        }

        private bool isEmailValid(string email)
        {
            int indexOfAtSign = email.IndexOf("@");
            var local = email.Substring(indexOfAtSign > 0 ? indexOfAtSign : email.Length - 1);
            return local.Contains(".");
        }

        private void textBox_TextChanged(object sender, KeyPressEventArgs e)
        {
            if ((Keys)e.KeyChar == Keys.Enter)
            {
                loginBtn_Click(sender, e);
            }
        }

        private void textBox_ResizeToContent(object sender, EventArgs e)
        {
            var textBox = sender as TextBox;
            Size size = TextRenderer.MeasureText(textBox.Text, textBox.Font);
            //keep within window
            textBox.Width = this.loginGroupBox.Width - 20 < size.Width ? this.loginGroupBox.Width - 20 : size.Width;
            textBox.Height = this.loginGroupBox.Height - 20 < size.Height ? this.loginGroupBox.Height - 20 : size.Height;
        }
    }
}
